name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v1
            - name: Compile LaTeX document
              uses: dante-ev/latex-action@master
              with:
                  working_directory: paper
                  root_file: main.tex
            - name: Upload pdf
              uses: actions/upload-artifact@v2
              with:
                  name: main.pdf
                  path: paper/main.pdf
            - name: Send slack notification
              uses: rtCamp/action-slack-notify@v2.0.2
              env:
                SLACK_WEBHOOK: https://hooks.slack.com/services/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
                SLACK_USERNAME: Compile bot
                SLACK_TITLE: PDF compiled!
                SLACK_MESSAGE: I was able to compile the most recent pdf. You can check it out here: https://github.com/cchang5/quantum_linear_programming/actions
